
services: 
  anaconda: 
     build:  .
     container_name: anaconda-notebook 
     env_file:
       - .env
     ports: 
        - "${JUPYTER_PORT}:${JUPYTER_PORT}"
     volumes: 
        - ./notebooks:/opt/notebooks
     command: jupyter lab --notebook-dir=/opt/notebooks --ip=0.0.0.0 --no-browser  --allow-root 
