name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - jupyter
  - jupyterlab
  - ipykernel
  - python-dotenv
  - requests 
  - beautifulsoup4
  - ipython
  - pip
  - pip:
      - openai>=1.30.0
      - gradio>=3.30.0